### ISSUE TITLE
Thank you!! ✨✨🍰✨✨

### ISSUE THREAD

**Issue by nilp0inter** [MiSTer-devel/Amstrad-PCW_MiSTer#1]
Thank you for recreating this!  With this one I now have access again to all the computers of my childhood within MiSTer.  And in my CRT it just looks like the old thing.

Thank you, thank you, thank you.

P.S. This is not an issue, you can close it :)

**Comment by steddyman** [comment]
Thanks for letting me know it worked for you and you like it.  You made my day :)
